
  
INSERT INTO STUDENT (STUDENT_NAME, CITY, PHONE_NUMBER) VALUES ('RAVI', 'CHENNAI', '9876543210');


INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_NAME) VALUES (1, 'JAVA');
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_NAME) VALUES (1, 'ANGULAR');